version: 2
updates:
  # Dependências Python (pyproject.toml) agrupadas em 1 único PR mensal
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "python"
    groups:
      python-dependencies:
        patterns:
          - "*"

  # Dependências Frontend (frontend/package.json) agrupadas em 1 único PR mensal
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "frontend"
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  # Ações do GitHub Actions (.github/workflows) agrupadas em 1 único PR mensal
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ci/cd"
    groups:
      actions-dependencies:
        patterns:
          - "*"
